/* Auto-generated by scripts/build-afrimedqa-bank.py — do not edit by hand */
import type { Quiz } from "./quiz-types";
import afrimedQuizzes from "../data/afrimedqa-quizzes.json";

export const QUIZZES: Quiz[] = afrimedQuizzes as Quiz[];
