/* Auto-generated by scripts/build-afrimedqa-bank.py — do not edit by hand */
import type { Quiz } from "./quiz-types";
import afrimedQuizzes from "../data/afrimedqa-quizzes.json";
import clinicalImageQuizzes from "../data/clinical-image-quizzes.bank.json";

export const QUIZZES: Quiz[] = [
  ...(afrimedQuizzes as Quiz[]),
  ...(clinicalImageQuizzes as Quiz[]),
];
